export { Factory } from "./Factory";
export type { IFactory } from "./Factory";
export { Depot } from "./Depot";
export type { IDepot } from "./Depot";
export { Truck } from "./Truck";
export type { ITruck } from "./Truck";
export { Product } from "./Product";
export type { IProduct } from "./Product";
export { Stock } from "./Stock";
export type { IStock } from "./Stock";
export { Transfer } from "./Transfer";
export type { ITransfer } from "./Transfer";
export { TruckLoad } from "./TruckLoad";
export type { ITruckLoad } from "./TruckLoad";
export { Sale } from "./Sale";
export type { ISale } from "./Sale";
export { Cost } from "./Cost";
export type { ICost } from "./Cost";
export { User } from "./User";
export type { IUser } from "./User";
export { ActivityLog } from "./ActivityLog";
export type { IActivityLog } from "./ActivityLog";
export { Production } from "./Production";
export type { IProduction } from "./Production";
export { PosDevice } from "./PosDevice";
export type { IPosDevice } from "./PosDevice";
export { PaymentTransaction } from "./PaymentTransaction";
export type { IPaymentTransaction } from "./PaymentTransaction";
export { Wastage } from "./Wastage";
export type { IWastage } from "./Wastage";
export { Customer } from "./Customer";
export type { ICustomer } from "./Customer";
export { Staff } from "./Staff";
export type { IStaff } from "./Staff";
export { Supplier } from "./Supplier";
export type { ISupplier } from "./Supplier";
export { RawMaterial } from "./RawMaterial";
export type { IRawMaterial, ICustomFieldDef } from "./RawMaterial";
export { ServiceRecord } from "./ServiceRecord";
export type { IServiceRecord } from "./ServiceRecord";
export { ScheduledOperation } from "./ScheduledOperation";
export type { IScheduledOperation } from "./ScheduledOperation";

// ─── Connector gears ──────────────────────────────────────
export { StaffUserLink } from "./StaffUserLink";
export type { IStaffUserLink } from "./StaffUserLink";
export { StaffAssignment } from "./StaffAssignment";
export type { IStaffAssignment } from "./StaffAssignment";
export { DriverAssignment } from "./DriverAssignment";
export type { IDriverAssignment } from "./DriverAssignment";
export { UserRole } from "./UserRole";
export type { IUserRole } from "./UserRole";
export { CustomerAccount } from "./CustomerAccount";
export type { ICustomerAccount } from "./CustomerAccount";
export { PosDeviceAssignment } from "./PosDeviceAssignment";
export type { IPosDeviceAssignment } from "./PosDeviceAssignment";
export { SupplierContract } from "./SupplierContract";
export type { ISupplierContract } from "./SupplierContract";

// ─── New entity cogs ──────────────────────────────────────
export { Asset } from "./Asset";
export type { IAsset } from "./Asset";
export { Batch } from "./Batch";
export type { IBatch } from "./Batch";
export { DeliveryRoute } from "./DeliveryRoute";
export type { IDeliveryRoute } from "./DeliveryRoute";
export { NAFDACRecord } from "./NAFDACRecord";
export type { INAFDACRecord } from "./NAFDACRecord";

// ─── New transactional models ─────────────────────────────
export { PurchaseOrder } from "./PurchaseOrder";
export type { IPurchaseOrder, IPurchaseOrderItem } from "./PurchaseOrder";
export type { IPaymentEntry as IPOPaymentEntry } from "./PurchaseOrder";
export { GoodsReceivedNote } from "./GoodsReceivedNote";
export type { IGoodsReceivedNote, IGRNItem } from "./GoodsReceivedNote";
export { BillOfMaterials } from "./BillOfMaterials";
export type { IBillOfMaterials, IBOMItem } from "./BillOfMaterials";
export { QualityCheck } from "./QualityCheck";
export type { IQualityCheck, IQCParameter } from "./QualityCheck";
export { Invoice } from "./Invoice";
export type { IInvoice, IInvoiceItem } from "./Invoice";
export { PaymentReceipt } from "./PaymentReceipt";
export type { IPaymentReceipt } from "./PaymentReceipt";
export { FuelLog } from "./FuelLog";
export type { IFuelLog } from "./FuelLog";
export { Attendance } from "./Attendance";
export type { IAttendance } from "./Attendance";
export { Leave } from "./Leave";
export type { ILeave } from "./Leave";
export { Trip } from "./Trip";
export type { ITrip } from "./Trip";
export { PayrollRecord } from "./PayrollRecord";
export type { IPayrollRecord } from "./PayrollRecord";
export { DailyStock } from "./DailyStock";
export type { IDailyStock } from "./DailyStock";
export { DailyStockColumn } from "./DailyStockColumn";
export type { IDailyStockColumn } from "./DailyStockColumn";
export { DailyProduction } from "./DailyProduction";
export type { IDailyProduction } from "./DailyProduction";
export { CommissionedStaff } from "./CommissionedStaff";
export type { ICommissionedStaff } from "./CommissionedStaff";
export { CommissionedStaffRecord } from "./CommissionedStaffRecord";
export type { ICommissionedStaffRecord, IPaymentEntry, IDebtorEntry } from "./CommissionedStaffRecord";
export { RawMaterialStockMovement } from "./RawMaterialStockMovement";
export type { IRawMaterialStockMovement } from "./RawMaterialStockMovement";
export { RawMaterialBatch } from "./RawMaterialBatch";
export type { IRawMaterialBatch, IRawMaterialBatchConversion } from "./RawMaterialBatch";
export { RawMaterialConsumption } from "./RawMaterialConsumption";
export type { IRawMaterialConsumption, IConsumptionAllocation } from "./RawMaterialConsumption";
export { SupplierLedger } from "./SupplierLedger";
export type { ISupplierLedger } from "./SupplierLedger";
